### ISSUE TITLE
Why is Angular a peer dependency?

### ISSUE THREAD

**Issue by farah** [transferwise/neptune-web#1479]
I use this library for a project and when I decided to bump the versions I got a lot of dependency errors. Root cause seems to be @transferwise/icons library has angular as a peer dependency. 

Was this intentional? Any work arounds?

**Comment by dozortsev** [comment]
Hey

`@transferwise/icons` provides icons for both React and Angular envs, if you don't use Angular just don't install the library

see usage and Sandbox demos in readme.md https://github.com/transferwise/icons#usage
