### ISSUE TITLE
integration with https://api-docs.transferwise.com/#recipient-accounts-requirements

### ISSUE THREAD

**Issue by pilot4u** [transferwise/neptune-web#148]
Hi,

I try to integrate Transferwize payout flow into our system
I see an endpoint which returns detailed UI spec
https://api.sandbox.transferwise.tech/v1/quotes/{quoteId}/account-requirements

But I cannot find any component at Neptune corresponding with this spec and creates the described UI.

Could you please update if there is a component which reads account-requirements API response and builds s screen with Neptune elements correspondingly?

Thanks,
David

**Comment by helendurranttw** [comment]
Hi David,

Thanks for reaching out, and I apologise for the slow reply. We do have a component in neptune-web that renders dynamic forms (JsonSchemaForm), but unfortunately that endpoint uses an older schema which the React component doesn't support.

We do have an [Angular component](https://github.com/transferwise/styleguide-components/tree/master/src/forms/fieldset) available that can render that schema. The [README](https://github.com/transferwise/styleguide-components) has links to more information and a demo.

Also in case it's any use, we have [example of a dynamic forms client for Android]((https://github.com/transferwise/banks-reference-android/tree/master/dynamicform)).

We are hoping to migrate this endpoint to the new version supported by the neptune-web components, but this probably won't happen for a while.

Sorry I couldn't be of more help.
