### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ofarukcaki** [transferwise/neptune-web#181]
What is the license of this repository? I didn't see any license and I need to know more about that before using it for a project

**Comment by andreapiras** [comment]
Hi, thanks for your request.
Please notice that our project is distributed under Apache2 license https://github.com/transferwise/neptune-web/blob/master/packages/components/LICENSE.md but it also contains a derivative of bootstrap which was licensed under MIT.
https://github.com/transferwise/bootstrap/blob/master/LICENSE
